[package]
name = "qcl"
description = "A Query Check Language written in Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1"
serde = "^1"
serde_json = "^1"

qcl = { path = "../qcl" }