[package]
name = "qcl"
description = "A Query Check Language written in Rust"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-test]
args = ["--", "--nocapture"]

[dependencies]
anyhow = "^1"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"

[[bin]]
name = "qcl"
path = "src/bin/main.rs"